-- ============================================================================
-- Teacher-CMS — full schema rebuild for a FRESH hosted project
--
-- GENERATED by tools/build_hosted_sql.mjs. Do not edit; edit the migrations in
-- supabase/migrations/ and re-run the generator.
--
-- Every migration, in order, and NO sample data — unlike _full_setup_hosted.sql,
-- which stops at 000400 and seeds a demo teacher@example.com admin you do not
-- want in production.
--
-- Run on an EMPTY project: Dashboard -> SQL Editor -> New query -> paste -> Run.
--
-- AFTERWARDS, in this order:
--   1. Create the admin (teacher) user through Supabase Auth, then set
--      profiles.role = 'admin' for it. Do NOT insert into auth.users by hand:
--      manual inserts leave NULL token columns and every later login fails with
--      "Database error querying schema".
--   2. Create the storage buckets if the dashboard does not show them.
--   3. Point the clients at the new project — the URL and anon key must be
--      updated in THREE places: app/dart_define.json, the admin portal's Vercel
--      env (VITE_SUPABASE_URL / VITE_SUPABASE_ANON_KEY), and the serverless
--      function's env (SUPABASE_URL / SUPABASE_SERVICE_ROLE_KEY).
--   4. Rebuild and redeploy both clients. An app binary has its URL compiled in.
-- ============================================================================


-- ============================================================================
-- >>> migrations/20250601000000_init_extensions_and_helpers.sql
-- ============================================================================

-- 20250601000000_init_extensions_and_helpers.sql
-- Extensions, enum types, and table-independent helper functions.
-- This must run before the core schema (which uses these types/functions).

-- ── Extensions (Supabase keeps these in the "extensions" schema) ──────────────
create extension if not exists pgcrypto with schema extensions;  -- crypt(), gen_salt()
create extension if not exists pg_trgm  with schema extensions;  -- trigram search
create extension if not exists unaccent with schema extensions;  -- diacritic folding
-- gen_random_uuid() is built into Postgres 13+ (no extension needed).

-- ── Enum types ────────────────────────────────────────────────────────────────
do $$ begin
  create type public.user_role as enum ('student', 'admin');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.media_type as enum ('video', 'pdf', 'other');
exception when duplicate_object then null; end $$;

-- ── Arabic text normalization (search/sort helper) ────────────────────────────
-- Folds an Arabic string to a canonical form so search matches regardless of how
-- the text was typed:
--   * lowercases any embedded Latin characters
--   * unifies alef / hamza / yaa / taa-marbuta variants (alef forms->ا, ى ئ->ي, ؤ->و, ة->ه)
--   * strips tashkil (harakat, U+064B-U+065F, U+0670) and the tatweel mark (U+0640)
-- Marked IMMUTABLE so it can back a STORED generated column and a GIN index.
create or replace function public.normalize_arabic(input text)
returns text
language sql
immutable
as $$
  select case
    when input is null then null
    else regexp_replace(
           translate(lower(input), 'أإآٱىئؤةـ', 'ااااييوه'),
           E'[ً-ٰٟـ]', '', 'g'
         )
  end;
$$;

comment on function public.normalize_arabic(text)
  is 'Canonical Arabic form for search: folds alef/hamza/yaa/taa variants and strips diacritics.';

-- ── Generic updated_at bump trigger ───────────────────────────────────────────
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ============================================================================
-- >>> migrations/20250601000100_core_schema.sql
-- ============================================================================

-- 20250601000100_core_schema.sql
-- Core tables, foreign keys, indexes, and row-level triggers.
-- Depends on: 20250601000000 (enum types + helper functions).

-- ══════════════════════════════════════════════════════════════════════════════
-- profiles — one row per auth user; carries role (student/admin) and display info
-- ══════════════════════════════════════════════════════════════════════════════
create table public.profiles (
  id           uuid primary key references auth.users (id) on delete cascade,
  role         public.user_role not null default 'student',
  display_name text,
  avatar_url   text,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);
create index idx_profiles_role on public.profiles (role);

-- Is the *current* request an admin? SECURITY DEFINER so it reads profiles
-- without triggering RLS — this lets other tables' policies call it safely
-- (no recursion) and keeps the role check in one place.
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

-- Auto-create a profile row whenever a new auth user signs up.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, display_name)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'display_name', new.email))
  on conflict (id) do nothing;
  return new;
end;
$$;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- Guard against privilege escalation: a signed-in non-admin cannot change a
-- profile's role. Trusted server contexts (no JWT -> auth.uid() is null, e.g.
-- the service role or seeding) are allowed through.
create or replace function public.enforce_profile_role()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.role is distinct from old.role
     and auth.uid() is not null
     and not public.is_admin() then
    raise exception 'only admins can change a profile role';
  end if;
  return new;
end;
$$;
create trigger profiles_guard_role
  before update on public.profiles
  for each row execute function public.enforce_profile_role();

create trigger profiles_set_updated_at
  before update on public.profiles
  for each row execute function public.set_updated_at();

-- ══════════════════════════════════════════════════════════════════════════════
-- categories -> subcategories  (content taxonomy)
-- ══════════════════════════════════════════════════════════════════════════════
create table public.categories (
  id         uuid primary key default gen_random_uuid(),
  name       text not null,
  slug       text not null unique,
  icon       text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index idx_categories_sort on public.categories (sort_order);

create trigger categories_set_updated_at
  before update on public.categories
  for each row execute function public.set_updated_at();

create table public.subcategories (
  id          uuid primary key default gen_random_uuid(),
  category_id uuid not null references public.categories (id) on delete cascade,
  name        text not null,
  slug        text not null,
  sort_order  integer not null default 0,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  unique (category_id, slug)
);
create index idx_subcategories_category on public.subcategories (category_id);
create index idx_subcategories_sort on public.subcategories (sort_order);

create trigger subcategories_set_updated_at
  before update on public.subcategories
  for each row execute function public.set_updated_at();

-- ══════════════════════════════════════════════════════════════════════════════
-- tags — freeform labels
-- ══════════════════════════════════════════════════════════════════════════════
create table public.tags (
  id         uuid primary key default gen_random_uuid(),
  name       text not null,
  slug       text not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger tags_set_updated_at
  before update on public.tags
  for each row execute function public.set_updated_at();

-- ══════════════════════════════════════════════════════════════════════════════
-- posts — the main content unit
-- ══════════════════════════════════════════════════════════════════════════════
create table public.posts (
  id             uuid primary key default gen_random_uuid(),
  title          text not null,
  body           text,                    -- markdown / rich text
  subcategory_id uuid not null references public.subcategories (id) on delete restrict,
  author_id      uuid references public.profiles (id) on delete set null,
  published      boolean not null default false,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now(),
  -- Normalized title+body for Arabic-aware search (see normalize_arabic()).
  search_text    text generated always as (
    public.normalize_arabic(coalesce(title, '') || ' ' || coalesce(body, ''))
  ) stored
);
create index idx_posts_subcategory      on public.posts (subcategory_id);
create index idx_posts_author           on public.posts (author_id);
create index idx_posts_published_created on public.posts (published, created_at desc);
create index idx_posts_search           on public.posts using gin (search_text extensions.gin_trgm_ops);

create trigger posts_set_updated_at
  before update on public.posts
  for each row execute function public.set_updated_at();

-- ══════════════════════════════════════════════════════════════════════════════
-- post_tags — many-to-many posts <-> tags
-- ══════════════════════════════════════════════════════════════════════════════
create table public.post_tags (
  post_id uuid not null references public.posts (id) on delete cascade,
  tag_id  uuid not null references public.tags (id) on delete cascade,
  primary key (post_id, tag_id)
);
create index idx_post_tags_tag on public.post_tags (tag_id);

-- ══════════════════════════════════════════════════════════════════════════════
-- media — files attached to a post (video / pdf / other)
-- ══════════════════════════════════════════════════════════════════════════════
create table public.media (
  id           uuid primary key default gen_random_uuid(),
  post_id      uuid not null references public.posts (id) on delete cascade,
  type         public.media_type not null,
  storage_path text,        -- object path within the "media" storage bucket, or
  external_url text,        -- an external/embedded URL — at least one is required
  display_name text,
  sort_order   integer not null default 0,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  constraint media_has_source check (storage_path is not null or external_url is not null)
);
create index idx_media_post      on public.media (post_id);
create index idx_media_post_sort on public.media (post_id, sort_order);

create trigger media_set_updated_at
  before update on public.media
  for each row execute function public.set_updated_at();

-- ══════════════════════════════════════════════════════════════════════════════
-- playlists -> playlist_items  (ordered collections of posts)
-- ══════════════════════════════════════════════════════════════════════════════
create table public.playlists (
  id          uuid primary key default gen_random_uuid(),
  title       text not null,
  description text,
  cover_image text,
  published   boolean not null default false,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
create index idx_playlists_published on public.playlists (published);

create trigger playlists_set_updated_at
  before update on public.playlists
  for each row execute function public.set_updated_at();

create table public.playlist_items (
  id          uuid primary key default gen_random_uuid(),
  playlist_id uuid not null references public.playlists (id) on delete cascade,
  post_id     uuid not null references public.posts (id) on delete cascade,
  position    integer not null,
  created_at  timestamptz not null default now(),
  unique (playlist_id, post_id),
  -- Deferrable so a whole playlist can be re-ordered inside one transaction.
  constraint playlist_items_position_unique unique (playlist_id, position)
    deferrable initially deferred
);
create index idx_playlist_items_playlist on public.playlist_items (playlist_id, position);
create index idx_playlist_items_post     on public.playlist_items (post_id);

-- ══════════════════════════════════════════════════════════════════════════════
-- view_history — one row per (student, post); "continue where you left off"
-- ══════════════════════════════════════════════════════════════════════════════
create table public.view_history (
  student_id       uuid not null references public.profiles (id) on delete cascade,
  post_id          uuid not null references public.posts (id) on delete cascade,
  progress_seconds integer not null default 0 check (progress_seconds >= 0),
  created_at       timestamptz not null default now(),
  last_viewed_at   timestamptz not null default now(),
  primary key (student_id, post_id)
);
create index idx_view_history_recent on public.view_history (student_id, last_viewed_at desc);
create index idx_view_history_post   on public.view_history (post_id);

-- Bump last_viewed_at on every update (re-view or progress change).
create or replace function public.touch_last_viewed()
returns trigger
language plpgsql
as $$
begin
  new.last_viewed_at = now();
  return new;
end;
$$;
create trigger view_history_touch
  before update on public.view_history
  for each row execute function public.touch_last_viewed();

-- ══════════════════════════════════════════════════════════════════════════════
-- achievements -> user_achievements
-- ══════════════════════════════════════════════════════════════════════════════
create table public.achievements (
  id          uuid primary key default gen_random_uuid(),
  code        text not null unique,    -- stable identifier the app references
  title       text not null,
  description text,
  icon        text,
  sort_order  integer not null default 0,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create trigger achievements_set_updated_at
  before update on public.achievements
  for each row execute function public.set_updated_at();

create table public.user_achievements (
  student_id     uuid not null references public.profiles (id) on delete cascade,
  achievement_id uuid not null references public.achievements (id) on delete cascade,
  unlocked_at    timestamptz not null default now(),
  primary key (student_id, achievement_id)
);
create index idx_user_achievements_achievement on public.user_achievements (achievement_id);

-- ══════════════════════════════════════════════════════════════════════════════
-- Base privileges for the API roles. Row visibility is governed by RLS, which is
-- enabled in the next migration; these grants just let the roles attempt access.
-- ══════════════════════════════════════════════════════════════════════════════
grant usage on schema public to anon, authenticated;
grant select on all tables in schema public to anon;
grant select, insert, update, delete on all tables in schema public to authenticated;
grant all on all tables in schema public to service_role;
grant execute on function public.is_admin()        to anon, authenticated;
grant execute on function public.normalize_arabic(text) to anon, authenticated;

-- GoTrue runs as `supabase_auth_admin` and fires on_auth_user_created (which calls
-- public.handle_new_user) whenever it inserts a new auth user. That role therefore
-- needs to see the public schema and execute the function; without these grants,
-- GoTrue can't reflect the auth schema and every auth request (login included)
-- fails with "Database error querying schema".
grant usage on schema public to supabase_auth_admin;
grant execute on function public.handle_new_user() to supabase_auth_admin;

-- ============================================================================
-- >>> migrations/20250601000200_rls_policies.sql
-- ============================================================================

-- 20250601000200_rls_policies.sql
-- Row Level Security. Access model:
--   * anon + authenticated may READ published content (free, open access).
--   * admins (profiles.role = 'admin') may do everything.
--   * a student may read/write only their OWN view_history and user_achievements.
-- Depends on: 20250601000100 (tables + public.is_admin()).

alter table public.profiles          enable row level security;
alter table public.categories        enable row level security;
alter table public.subcategories     enable row level security;
alter table public.tags              enable row level security;
alter table public.posts             enable row level security;
alter table public.post_tags         enable row level security;
alter table public.media             enable row level security;
alter table public.playlists         enable row level security;
alter table public.playlist_items    enable row level security;
alter table public.view_history      enable row level security;
alter table public.achievements      enable row level security;
alter table public.user_achievements enable row level security;

-- ── profiles ──────────────────────────────────────────────────────────────────
-- Readable: your own row, any admin (teacher) row, and everything for admins.
create policy "profiles_select" on public.profiles
  for select to authenticated
  using (id = auth.uid() or role = 'admin' or public.is_admin());
create policy "profiles_insert_self" on public.profiles
  for insert to authenticated
  with check (id = auth.uid());
-- Self-updates allowed; the profiles_guard_role trigger still blocks role changes.
create policy "profiles_update_self_or_admin" on public.profiles
  for update to authenticated
  using (id = auth.uid() or public.is_admin())
  with check (id = auth.uid() or public.is_admin());
create policy "profiles_delete_admin" on public.profiles
  for delete to authenticated
  using (public.is_admin());

-- ── Lookup tables: public read, admin write ───────────────────────────────────
create policy "categories_read" on public.categories
  for select to anon, authenticated using (true);
create policy "categories_admin_write" on public.categories
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

create policy "subcategories_read" on public.subcategories
  for select to anon, authenticated using (true);
create policy "subcategories_admin_write" on public.subcategories
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

create policy "tags_read" on public.tags
  for select to anon, authenticated using (true);
create policy "tags_admin_write" on public.tags
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

create policy "achievements_read" on public.achievements
  for select to anon, authenticated using (true);
create policy "achievements_admin_write" on public.achievements
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- ── posts: read published (or admin), admin write ─────────────────────────────
create policy "posts_read_published_or_admin" on public.posts
  for select to anon, authenticated
  using (published or public.is_admin());
create policy "posts_admin_write" on public.posts
  for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

-- ── post_tags / media: visible when the parent post is visible; admin write ───
create policy "post_tags_read" on public.post_tags
  for select to anon, authenticated
  using (exists (
    select 1 from public.posts p
    where p.id = post_id and (p.published or public.is_admin())
  ));
create policy "post_tags_admin_write" on public.post_tags
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

create policy "media_read" on public.media
  for select to anon, authenticated
  using (exists (
    select 1 from public.posts p
    where p.id = post_id and (p.published or public.is_admin())
  ));
create policy "media_admin_write" on public.media
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- ── playlists / playlist_items: read published (or admin), admin write ────────
create policy "playlists_read_published_or_admin" on public.playlists
  for select to anon, authenticated
  using (published or public.is_admin());
create policy "playlists_admin_write" on public.playlists
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

create policy "playlist_items_read" on public.playlist_items
  for select to anon, authenticated
  using (exists (
    select 1 from public.playlists pl
    where pl.id = playlist_id and (pl.published or public.is_admin())
  ));
create policy "playlist_items_admin_write" on public.playlist_items
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- ── view_history: a student owns their rows; admins may read/manage all ───────
create policy "view_history_select_own_or_admin" on public.view_history
  for select to authenticated
  using (student_id = auth.uid() or public.is_admin());
create policy "view_history_insert_own" on public.view_history
  for insert to authenticated
  with check (student_id = auth.uid());
create policy "view_history_update_own" on public.view_history
  for update to authenticated
  using (student_id = auth.uid())
  with check (student_id = auth.uid());
create policy "view_history_delete_own_or_admin" on public.view_history
  for delete to authenticated
  using (student_id = auth.uid() or public.is_admin());
create policy "view_history_admin_manage" on public.view_history
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- ── user_achievements: a student owns their rows; admins may read/manage all ──
create policy "user_achievements_select_own_or_admin" on public.user_achievements
  for select to authenticated
  using (student_id = auth.uid() or public.is_admin());
create policy "user_achievements_insert_own" on public.user_achievements
  for insert to authenticated
  with check (student_id = auth.uid());
create policy "user_achievements_delete_own_or_admin" on public.user_achievements
  for delete to authenticated
  using (student_id = auth.uid() or public.is_admin());
create policy "user_achievements_admin_manage" on public.user_achievements
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- ============================================================================
-- >>> migrations/20250601000300_storage.sql
-- ============================================================================

-- 20250601000300_storage.sql
-- Storage buckets and object-level access policies.
--
--   media          : PRIVATE bucket for post attachments (video/pdf/other).
--                    Readable by anyone only when the owning post is published;
--                    writable by admins only.
--   public-assets  : PUBLIC bucket for non-sensitive images (category icons,
--                    playlist covers, avatars). World-readable; admin write.
--
-- Convention: media.storage_path holds the object's path (the storage.objects
-- "name") within the "media" bucket — that linkage is what gates read access.
-- Depends on: 20250601000100 (public.media / public.posts + public.is_admin()).

insert into storage.buckets (id, name, public)
values ('media', 'media', false)
on conflict (id) do nothing;

insert into storage.buckets (id, name, public)
values ('public-assets', 'public-assets', true)
on conflict (id) do nothing;

-- ── media bucket: read only published media (or admin) ────────────────────────
create policy "media_read_published_or_admin" on storage.objects
  for select to anon, authenticated
  using (
    bucket_id = 'media'
    and (
      public.is_admin()
      or exists (
        select 1
        from public.media m
        join public.posts p on p.id = m.post_id
        where m.storage_path = storage.objects.name
          and p.published
      )
    )
  );

create policy "media_admin_insert" on storage.objects
  for insert to authenticated
  with check (bucket_id = 'media' and public.is_admin());

create policy "media_admin_update" on storage.objects
  for update to authenticated
  using (bucket_id = 'media' and public.is_admin())
  with check (bucket_id = 'media' and public.is_admin());

create policy "media_admin_delete" on storage.objects
  for delete to authenticated
  using (bucket_id = 'media' and public.is_admin());

-- ── public-assets bucket: world read, admin write ─────────────────────────────
-- (Bucket is public=true, so reads are served via the public URL; this SELECT
-- policy covers the storage API / listing path.)
create policy "public_assets_read" on storage.objects
  for select to anon, authenticated
  using (bucket_id = 'public-assets');

create policy "public_assets_admin_insert" on storage.objects
  for insert to authenticated
  with check (bucket_id = 'public-assets' and public.is_admin());

create policy "public_assets_admin_update" on storage.objects
  for update to authenticated
  using (bucket_id = 'public-assets' and public.is_admin())
  with check (bucket_id = 'public-assets' and public.is_admin());

create policy "public_assets_admin_delete" on storage.objects
  for delete to authenticated
  using (bucket_id = 'public-assets' and public.is_admin());

-- ============================================================================
-- >>> migrations/20250601000400_achievements_engine.sql
-- ============================================================================

-- 20250601000400_achievements_engine.sql
-- Server-side achievement detection.
--
-- Adds a lightweight daily-activity log (for streaks), ensures the starter
-- achievement set exists, and exposes claim_achievements(): the app calls it
-- after activity, and it records today's activity, grants any newly-earned
-- achievements, and RETURNS the freshly granted ones so the client can
-- celebrate exactly what was just unlocked.
--
-- Detection lives in Postgres (authoritative): the client cannot fabricate an
-- unlock — it can only ask the server to evaluate the rules for the current user.
--
-- Depends on: 20250601000100 (tables + is_admin()), 20250601000200 (RLS).

-- ── student_activity: one row per (student, calendar day) of activity ─────────
-- view_history keeps only the latest timestamp per post, which can't express a
-- multi-day streak; this small log records each active day instead.
create table if not exists public.student_activity (
  student_id    uuid not null references public.profiles (id) on delete cascade,
  activity_date date not null default current_date,
  primary key (student_id, activity_date)
);
create index if not exists idx_student_activity_student
  on public.student_activity (student_id, activity_date desc);

alter table public.student_activity enable row level security;

create policy "student_activity_select_own_or_admin" on public.student_activity
  for select to authenticated
  using (student_id = auth.uid() or public.is_admin());
create policy "student_activity_insert_own" on public.student_activity
  for insert to authenticated
  with check (student_id = auth.uid());
create policy "student_activity_admin_manage" on public.student_activity
  for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

grant select, insert on public.student_activity to authenticated;

-- ── Starter achievement definitions (idempotent; the app keys off `code`) ─────
-- The two codes that also appear in seed.sql reuse the seed UUIDs, so seed's
-- `on conflict (id) do nothing` stays correct and no seed edit is needed.
insert into public.achievements (id, code, title, description, icon, sort_order) values
  ('fa111111-1111-1111-1111-111111111111', 'first_view',     'الخطوة الأولى',      'شاهدت أول درس لك.',        'star',   1),
  ('fa444444-4444-4444-4444-444444444444', 'views_25',       'متعلّم مثابر',       'شاهدت 25 درسًا.',          'school', 2),
  ('fa555555-5555-5555-5555-555555555555', 'streak_5_days',  'خمسة أيام متتالية',  'تعلّمت 5 أيام متتالية.',   'fire',   3),
  ('fa333333-3333-3333-3333-333333333333', 'first_playlist', 'رحلة منظَّمة',        'أكملت أول قائمة تشغيل.',   'trophy', 4)
on conflict (code) do nothing;

-- ── claim_achievements(): record activity, grant newly-earned, return them ────
-- SECURITY DEFINER so it can write user_achievements regardless of the caller's
-- RLS; it always acts on the current user (auth.uid()) and never trusts input.
create or replace function public.claim_achievements()
returns table (code text, title text, description text, icon text)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_student uuid := auth.uid();
begin
  if v_student is null then
    return; -- not signed in: nothing to claim
  end if;

  -- Record today's activity (drives the streak rule).
  insert into public.student_activity (student_id, activity_date)
  values (v_student, current_date)
  on conflict do nothing;

  return query
  with viewed as (
    select count(distinct vh.post_id) as n
    from public.view_history vh
    where vh.student_id = v_student
  ),
  days as (
    select distinct activity_date as d
    from public.student_activity
    where student_id = v_student
  ),
  -- Gaps-and-islands: consecutive days share the same (date - row_number()).
  islands as (
    select d, d - (row_number() over (order by d))::int as grp
    from days
  ),
  streak as (
    select count(*) as len
    from islands
    where grp = (select grp from islands where d = current_date)
  ),
  completed_playlist as (
    select exists (
      select 1
      from public.playlists pl
      where pl.published
        and exists (
          select 1 from public.playlist_items pi where pi.playlist_id = pl.id
        )
        and not exists (
          select 1
          from public.playlist_items pi
          where pi.playlist_id = pl.id
            and pi.post_id not in (
              select vh.post_id
              from public.view_history vh
              where vh.student_id = v_student
            )
        )
    ) as done
  ),
  earned as (
    select a.id
    from public.achievements a
    where (a.code = 'first_view'     and (select n   from viewed) >= 1)
       or (a.code = 'five_views'     and (select n   from viewed) >= 5)
       or (a.code = 'views_25'       and (select n   from viewed) >= 25)
       or (a.code = 'streak_5_days'  and (select len from streak) >= 5)
       or (a.code = 'first_playlist' and (select done from completed_playlist))
  ),
  inserted as (
    insert into public.user_achievements (student_id, achievement_id)
    select v_student, e.id from earned e
    on conflict (student_id, achievement_id) do nothing
    returning achievement_id
  )
  select a.code, a.title, a.description, a.icon
  from inserted i
  join public.achievements a on a.id = i.achievement_id
  order by a.sort_order;
end;
$$;

grant execute on function public.claim_achievements() to authenticated;

-- ============================================================================
-- >>> migrations/20250601000500_view_history_seen.sql
-- ============================================================================

-- 20250601000500_view_history_seen.sql
-- Separate "seen" from "progress" on view_history.
--
-- Until now a row's mere existence meant "seen", which coupled the two: saving a
-- video resume position implicitly marked a post seen. This adds an explicit
-- `seen` flag so the two are independent:
--   * progress_seconds — video resume position, saved automatically as you watch
--   * seen             — the student's deliberate "I've seen this" (the app button)
--
-- A post can therefore have resume progress without being "seen", and marking it
-- seen no longer depends on having watched anything.
--
-- Depends on: 20250601000100 (view_history), 20250601000400 (claim_achievements).

-- Add the column and backfill only on first apply, so existing rows (which meant
-- "seen" under the old model) become seen = true while new rows default to false.
do $$
begin
  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public'
      and table_name = 'view_history'
      and column_name = 'seen'
  ) then
    alter table public.view_history add column seen boolean;
    update public.view_history set seen = true;
    alter table public.view_history alter column seen set default false;
    alter table public.view_history alter column seen set not null;
  end if;
end $$;

-- Speeds up the "how many seen" / playlist-completion checks below.
create index if not exists idx_view_history_seen
  on public.view_history (student_id) where seen;

-- Recount views and playlist completion from SEEN rows only (was: any row).
create or replace function public.claim_achievements()
returns table (code text, title text, description text, icon text)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_student uuid := auth.uid();
begin
  if v_student is null then
    return; -- not signed in: nothing to claim
  end if;

  -- Record today's activity (drives the streak rule).
  insert into public.student_activity (student_id, activity_date)
  values (v_student, current_date)
  on conflict do nothing;

  return query
  with viewed as (
    select count(distinct vh.post_id) as n
    from public.view_history vh
    where vh.student_id = v_student and vh.seen
  ),
  days as (
    select distinct activity_date as d
    from public.student_activity
    where student_id = v_student
  ),
  -- Gaps-and-islands: consecutive days share the same (date - row_number()).
  islands as (
    select d, d - (row_number() over (order by d))::int as grp
    from days
  ),
  streak as (
    select count(*) as len
    from islands
    where grp = (select grp from islands where d = current_date)
  ),
  completed_playlist as (
    select exists (
      select 1
      from public.playlists pl
      where pl.published
        and exists (
          select 1 from public.playlist_items pi where pi.playlist_id = pl.id
        )
        and not exists (
          select 1
          from public.playlist_items pi
          where pi.playlist_id = pl.id
            and pi.post_id not in (
              select vh.post_id
              from public.view_history vh
              where vh.student_id = v_student and vh.seen
            )
        )
    ) as done
  ),
  earned as (
    select a.id
    from public.achievements a
    where (a.code = 'first_view'     and (select n   from viewed) >= 1)
       or (a.code = 'five_views'     and (select n   from viewed) >= 5)
       or (a.code = 'views_25'       and (select n   from viewed) >= 25)
       or (a.code = 'streak_5_days'  and (select len from streak) >= 5)
       or (a.code = 'first_playlist' and (select done from completed_playlist))
  ),
  inserted as (
    insert into public.user_achievements (student_id, achievement_id)
    select v_student, e.id from earned e
    on conflict (student_id, achievement_id) do nothing
    returning achievement_id
  )
  select a.code, a.title, a.description, a.icon
  from inserted i
  join public.achievements a on a.id = i.achievement_id
  order by a.sort_order;
end;
$$;

grant execute on function public.claim_achievements() to authenticated;

-- ============================================================================
-- >>> migrations/20250601000600_content_groups.sql
-- ============================================================================

-- 20250601000600_content_groups.sql
-- Group-based content visibility. A student belongs to zero or more GROUPS; each
-- group is granted access to whole CATEGORIES and/or individual SUBCATEGORIES. A
-- student sees the UNION of what all their groups allow. A student in no group (or
-- whose groups grant nothing) sees NO content — access is opt-in.
--
-- Visibility is enforced in RLS (authoritative): the app's queries can't widen it.
-- Admins (profiles.role = 'admin') bypass all of it and see everything.
-- Depends on: 20250601000100 (tables, is_admin(), set_updated_at()).

-- ══════════════════════════════════════════════════════════════════════════════
-- Tables
-- ══════════════════════════════════════════════════════════════════════════════
create table if not exists public.groups (
  id          uuid primary key default gen_random_uuid(),
  name        text not null,
  description text,
  sort_order  integer not null default 0,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
create index if not exists idx_groups_sort on public.groups (sort_order);

drop trigger if exists groups_set_updated_at on public.groups;
create trigger groups_set_updated_at
  before update on public.groups
  for each row execute function public.set_updated_at();

-- Which students belong to a group (many-to-many).
create table if not exists public.group_members (
  group_id   uuid not null references public.groups (id) on delete cascade,
  student_id uuid not null references public.profiles (id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (group_id, student_id)
);
create index if not exists idx_group_members_student on public.group_members (student_id);

-- A group granted a WHOLE category — includes every current and future
-- subcategory under it.
create table if not exists public.group_categories (
  group_id    uuid not null references public.groups (id) on delete cascade,
  category_id uuid not null references public.categories (id) on delete cascade,
  created_at  timestamptz not null default now(),
  primary key (group_id, category_id)
);
create index if not exists idx_group_categories_category on public.group_categories (category_id);

-- A group granted a single subcategory (from a category it does not hold wholesale).
create table if not exists public.group_subcategories (
  group_id       uuid not null references public.groups (id) on delete cascade,
  subcategory_id uuid not null references public.subcategories (id) on delete cascade,
  created_at     timestamptz not null default now(),
  primary key (group_id, subcategory_id)
);
create index if not exists idx_group_subcategories_subcategory
  on public.group_subcategories (subcategory_id);

-- ══════════════════════════════════════════════════════════════════════════════
-- Visibility helpers. SECURITY DEFINER so they read the group tables without
-- tripping RLS (no recursion when a table's own policy calls them). STABLE so the
-- planner can cache within a statement. Both return true for admins.
-- ══════════════════════════════════════════════════════════════════════════════

-- Can the current user see this subcategory (and therefore posts inside it)?
create or replace function public.can_see_subcategory(subcat_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.is_admin() or exists (
    select 1
    from public.group_members gm
    join public.subcategories s on s.id = subcat_id
    where gm.student_id = auth.uid()
      and (
        exists (
          select 1 from public.group_categories gc
          where gc.group_id = gm.group_id and gc.category_id = s.category_id
        )
        or exists (
          select 1 from public.group_subcategories gs
          where gs.group_id = gm.group_id and gs.subcategory_id = subcat_id
        )
      )
  );
$$;

-- Can the current user see this category at all? True if any of their groups holds
-- the whole category or any subcategory within it — used so Browse hides empty
-- categories.
create or replace function public.can_see_category(cat_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.is_admin() or exists (
    select 1
    from public.group_members gm
    where gm.student_id = auth.uid()
      and (
        exists (
          select 1 from public.group_categories gc
          where gc.group_id = gm.group_id and gc.category_id = cat_id
        )
        or exists (
          select 1 from public.group_subcategories gs
          join public.subcategories s on s.id = gs.subcategory_id
          where gs.group_id = gm.group_id and s.category_id = cat_id
        )
      )
  );
$$;

-- ══════════════════════════════════════════════════════════════════════════════
-- Privileges (blanket grants in 000100 predate these tables, so grant explicitly).
-- Row visibility is still governed by the RLS policies below.
-- ══════════════════════════════════════════════════════════════════════════════
grant select on public.groups, public.group_members,
                 public.group_categories, public.group_subcategories to anon;
grant select, insert, update, delete on public.groups, public.group_members,
                 public.group_categories, public.group_subcategories to authenticated;
grant all on public.groups, public.group_members,
             public.group_categories, public.group_subcategories to service_role;
grant execute on function public.can_see_subcategory(uuid) to anon, authenticated;
grant execute on function public.can_see_category(uuid)    to anon, authenticated;

-- ══════════════════════════════════════════════════════════════════════════════
-- RLS on the new tables: only admins manage them from the client. (The student
-- serverless function uses service_role, which bypasses RLS, to assign members.)
-- ══════════════════════════════════════════════════════════════════════════════
alter table public.groups              enable row level security;
alter table public.group_members       enable row level security;
alter table public.group_categories    enable row level security;
alter table public.group_subcategories enable row level security;

drop policy if exists "groups_admin_all" on public.groups;
create policy "groups_admin_all" on public.groups
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "group_members_admin_all" on public.group_members;
create policy "group_members_admin_all" on public.group_members
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "group_categories_admin_all" on public.group_categories;
create policy "group_categories_admin_all" on public.group_categories
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "group_subcategories_admin_all" on public.group_subcategories;
create policy "group_subcategories_admin_all" on public.group_subcategories
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- ══════════════════════════════════════════════════════════════════════════════
-- Re-gate content reads by group visibility. These REPLACE the open "read
-- published" policies from 000200 (which let every signed-in user see everything).
-- ══════════════════════════════════════════════════════════════════════════════

-- categories: only those the user's groups can reach (admins: all).
drop policy if exists "categories_read" on public.categories;
create policy "categories_read" on public.categories
  for select to anon, authenticated
  using (public.can_see_category(id));

-- subcategories: only granted ones (admins: all).
drop policy if exists "subcategories_read" on public.subcategories;
create policy "subcategories_read" on public.subcategories
  for select to anon, authenticated
  using (public.can_see_subcategory(id));

-- posts: published AND in a visible subcategory (admins: all, incl. drafts).
drop policy if exists "posts_read_published_or_admin" on public.posts;
create policy "posts_read_published_or_admin" on public.posts
  for select to anon, authenticated
  using (public.is_admin() or (published and public.can_see_subcategory(subcategory_id)));

-- post_tags: visible when the parent post is visible.
drop policy if exists "post_tags_read" on public.post_tags;
create policy "post_tags_read" on public.post_tags
  for select to anon, authenticated
  using (exists (
    select 1 from public.posts p
    where p.id = post_id
      and (public.is_admin() or (p.published and public.can_see_subcategory(p.subcategory_id)))
  ));

-- media: visible when the parent post is visible.
drop policy if exists "media_read" on public.media;
create policy "media_read" on public.media
  for select to anon, authenticated
  using (exists (
    select 1 from public.posts p
    where p.id = post_id
      and (public.is_admin() or (p.published and public.can_see_subcategory(p.subcategory_id)))
  ));

-- playlist_items: a playlist stays readable, but only surfaces posts the student
-- is allowed to see (published playlist + published, visible post).
drop policy if exists "playlist_items_read" on public.playlist_items;
create policy "playlist_items_read" on public.playlist_items
  for select to anon, authenticated
  using (
    public.is_admin() or (
      exists (
        select 1 from public.playlists pl
        where pl.id = playlist_id and pl.published
      )
      and exists (
        select 1 from public.posts p
        where p.id = post_id
          and p.published
          and public.can_see_subcategory(p.subcategory_id)
      )
    )
  );

-- ============================================================================
-- >>> migrations/20250601000700_student_import_fields.sql
-- ============================================================================

-- 20250601000700_student_import_fields.sql
-- Roster fields for bulk student import from the teacher's Excel sheets.
--
-- The admin portal can import a workbook (one sheet per class) and create the
-- student accounts in bulk. Two identifying fields from that sheet are worth
-- keeping on the profile so an app account can later be reconciled with the
-- teacher's own roster:
--   • serial_number — الرقم التسلسلي (the student's serial in the class list)
--   • request_code  — كود الطلب     (the per-student request/enrolment code)
-- Both are free-form text (they may carry leading zeros or non-numeric forms),
-- nullable (pre-existing and manually-created students won't have them), and
-- admin-facing only — the student app never reads them.
-- Depends on: 20250601000100 (profiles table).

alter table public.profiles
  add column if not exists serial_number text,
  add column if not exists request_code  text;

comment on column public.profiles.serial_number is
  'الرقم التسلسلي from the teacher''s class sheet (bulk import). Free-form text.';
comment on column public.profiles.request_code is
  'كود الطلب from the teacher''s class sheet (bulk import). Free-form text.';

-- No RLS change needed: profiles policies already let admins read/write every
-- column and let a student read only their own row. These columns inherit that.

-- ============================================================================
-- >>> migrations/20250601000800_guest_content.sql
-- ============================================================================

-- 20250601000800_guest_content.sql
-- Guest access: a single shared "guest" student can browse one public category.
--
-- The app's sign-in screen has a "الدخول كضيف" (log in as guest) button that
-- signs in with a shared guest account. Content visibility is entirely
-- group-based (see 20250601000600_content_groups.sql): a student sees the union
-- of the categories/subcategories granted to their groups. So the "guest" is
-- just an ordinary student whose one group grants a single "guest" category.
--
-- This migration provisions the data side of that: the guest category, the
-- guest group, and the grant linking them. It is idempotent (fixed UUIDs +
-- `on conflict do nothing`), matching the style of seed.sql.
--
-- TWO MANUAL FOLLOW-UPS (can't be done safely in SQL):
--   (a) In the admin portal, author a subcategory + at least one PUBLISHED post
--       under the "guest" category. The category grant already covers any
--       subcategories added later, so no further grant is needed.
--   (b) In the الطلاب (Students) page, create the guest student account
--       (username = the app's GUEST_USERNAME dart-define, password = its
--       GUEST_PASSWORD) and assign it to the "الضيوف" group created below.
--       Auth users must be created via the Admin API — a raw auth.users insert
--       leaves NULL token columns and breaks login (the known login-500).
-- Depends on: 20250601000100 (categories) and 20250601000600 (groups + grants).

-- The public "guest" category. Renameable from the admin portal; the slug is
-- what matters as a stable handle.
insert into public.categories (id, name, slug, sort_order) values
  ('cccccccc-0000-4000-8000-000000000001', 'محتوى الضيف', 'guest', 1000)
on conflict (slug) do nothing;

-- The group every guest belongs to. sort_order 1000 keeps it out of the way in
-- the admin group list.
insert into public.groups (id, name, description, sort_order) values
  ('a0000000-0000-4000-8000-000000000001', 'الضيوف',
   'المجموعة الافتراضية لحساب الضيف — تمنح الوصول إلى فئة «محتوى الضيف».', 1000)
on conflict (id) do nothing;

-- Grant the whole guest category (incl. future subcategories) to the guest
-- group. Looked up by slug so it still works if a "guest" category already
-- existed under a different id (the insert above was then a no-op).
insert into public.group_categories (group_id, category_id)
select 'a0000000-0000-4000-8000-000000000001', c.id
from public.categories c
where c.slug = 'guest'
on conflict do nothing;
