// Regenerates the paste-ready SQL bundles in /supabase from the migration files.
//
//   node tools/build_hosted_sql.mjs
//
// The hosted Supabase dashboard has no migration runner — you paste SQL into the
// SQL Editor. These bundles exist so that is one paste instead of nine, and they
// are generated rather than hand-maintained so they cannot drift from
// supabase/migrations/, which stays the source of truth.
//
// Note the editor runs a pasted script as a SINGLE transaction: any error rolls
// the whole thing back. Every migration here is idempotent (create ... if not
// exists, drop policy if exists, on conflict do nothing), so a rolled-back run
// can simply be fixed and pasted again.

import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const MIGRATIONS = join(ROOT, 'supabase', 'migrations')

const all = readdirSync(MIGRATIONS)
  .filter((f) => f.endsWith('.sql'))
  .sort() // filename order is apply order, by design

function bundle(files, header) {
  let out = header + '\n'
  for (const file of files) {
    out += '\n-- ============================================================================\n'
    out += `-- >>> migrations/${file}\n`
    out += '-- ============================================================================\n\n'
    out += readFileSync(join(MIGRATIONS, file), 'utf8').replaceAll('\r\n', '\n').trimEnd() + '\n'
  }
  return out
}

const REBUILD_HEADER = `-- ============================================================================
-- Teacher-CMS — full schema rebuild for a FRESH hosted project
--
-- GENERATED by tools/build_hosted_sql.mjs. Do not edit; edit the migrations in
-- supabase/migrations/ and re-run the generator.
--
-- Every migration, in order, and NO sample data — unlike _full_setup_hosted.sql,
-- which stops at 000400 and seeds a demo teacher@example.com admin you do not
-- want in production.
--
-- Run on an EMPTY project: Dashboard -> SQL Editor -> New query -> paste -> Run.
--
-- AFTERWARDS, in this order:
--   1. Create the admin (teacher) user through Supabase Auth, then set
--      profiles.role = 'admin' for it. Do NOT insert into auth.users by hand:
--      manual inserts leave NULL token columns and every later login fails with
--      "Database error querying schema".
--   2. Create the storage buckets if the dashboard does not show them.
--   3. Point the clients at the new project — the URL and anon key must be
--      updated in THREE places: app/dart_define.json, the admin portal's Vercel
--      env (VITE_SUPABASE_URL / VITE_SUPABASE_ANON_KEY), and the serverless
--      function's env (SUPABASE_URL / SUPABASE_SERVICE_ROLE_KEY).
--   4. Rebuild and redeploy both clients. An app binary has its URL compiled in.
-- ============================================================================
`

const PENDING_HEADER = `-- ============================================================================
-- Teacher-CMS — pending hosted-DB migrations (000600, 000700, 000800)
--
-- GENERATED by tools/build_hosted_sql.mjs. Do not edit; edit the migrations in
-- supabase/migrations/ and re-run the generator.
--
-- For a project that already has 000000-000500. If you are starting from an
-- empty project, use _rebuild_all_hosted.sql instead.
--
-- Run via: Dashboard -> SQL Editor -> New query -> paste -> Run.
--
-- *** READ BEFORE RUNNING ***
-- 000600 switches content visibility to group-based. The moment it lands, every
-- student sees NOTHING until they are put in a group that has been granted
-- categories. Plan to create the groups and assign students immediately after,
-- in the admin portal (المجموعات then الطلاب).
-- ============================================================================
`

// Everything from 000600 onward — the migrations not yet applied to the hosted
// project. Compared numerically on the filename's timestamp prefix rather than by
// substring: a pattern like /_0006/ silently matches nothing here, because the
// prefix is one unbroken number (20250601000600_…), and an empty bundle is a
// worse failure than a loud one.
const FIRST_PENDING = 20250601000600n
const migrationId = (file) => BigInt(file.split('_')[0])
const pending = all.filter((f) => migrationId(f) >= FIRST_PENDING)
if (pending.length === 0) {
  console.error('No pending migrations matched — check FIRST_PENDING against the filenames.')
  process.exit(1)
}

const targets = [
  ['supabase/_rebuild_all_hosted.sql', bundle(all, REBUILD_HEADER), all],
  ['supabase/_apply_pending_hosted.sql', bundle(pending, PENDING_HEADER), pending],
]

for (const [path, content, files] of targets) {
  writeFileSync(join(ROOT, path), content)
  console.log(`${path}`)
  console.log(`  ${files.length} migration(s), ${content.split('\n').length} lines`)
  for (const f of files) console.log(`    ${f}`)
}
